name: "Sphinx Build"
on:
  push:
    branch:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        poetry install
        sudo apt-get install pandoc

    - name: Build documentation
      run: |
        cd sphinx
        poetry run make clean
        poetry run make html
        cd ..
        rm -rf docs
        mv sphinx/_build/html docs
        touch docs/.nojekyll
        ls -la docs

    - name: Push built docs
      run: |
        git config --global user.name 'jostmorgenstern'
        git config --global user.email 'jostmorgenstern@users.noreply.github.com'
        git add .
        git commit -am "Automated docs generation"
        git status
        git push origin main


