name: "Publish to PyPi"
on:
  release:
    types: [published]
    branches:
      - main
jobs:
  publish-dists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Build artifacts
      run: |
        poetry install
        poetry build

    - name: Publish dists
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

