name: "Publish to Test PyPi"
on:
  push:
    branches:
    - CI-testpypi
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Build artifacts
      run: |
        poetry install
        poetry build

    - name: Publish dists
      uses: pypa/gh-action-pypi-publish
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

